[database]
type = 'mysql'
host = '127.0.0.1'
port = 3306
user = 'root'
password = 'root'
database = 'gin_vue_admin_framework'
prefix = 'gvaf_'

[jwt]
secret = 'zYn2Kk0ouZ0qYh*J68@msM!AHs^()@A@OAK!3+_a2c5v5kt8^hsR'
expiresAt = '7' # 有效期/天
issuer = 'server'

[redis]
host = '127.0.0.1'
port = '6379'
password = ''
db = 1